### ISSUE TITLE
Preload doesn't work on Docker 2.0.0.0 [macOS Mojave]

### ISSUE THREAD

**Issue by FRVisser** [balena-io/balena-preload#193]
Hi, 

The preload function isn't able to start docker image on the latest stable Docker 2.0.0.0, on macOS Mojave 10.14.1.

It returns: 
```
Error starting daemon: error initializing graphdriver: driver not supported
```
Which seems to be an old Docker issue. I reverted to an older version of Docker and everything works like a charm (1.13.1 (15353))

To debug I also tried updating all components, which didn't resolve the issue. I updated Node (v11.4.0) and npm (6.4.1) and Belana-cli afterwards (9.4.0) hoping to get all new versions, there are no updates yet for Docker.

Full output

```
Building Docker preloader image. [========================] 100%



/ Creating preloader container
/ Starting preloader container
- Reading image information
1: Step 1/7 : FROM docker:17.10.0-ce-dind
 ---> 9769e0f3f9cb
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Using cache
 ---> 1ba613600810
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
 ---> 41124aaefbfb
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
 ---> ff360f39d233
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
 ---> 497d14a8b763
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 30466b3a1f39
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
 ---> 7888663415e9
Successfully built 7888663415e9
Successfully tagged balena/balena-preload:latest
Waiting for Docker to start...
Exception in thread background thread for pid 208:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmppe4ea8sb/docker --host=tcp://0.0.0.0:56017

  STDOUT:


  STDERR:
time="2018-12-13T09:49:44.170731602Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2018-12-13T09:49:44.173455723Z" level=info msg="libcontainerd: new containerd process, pid: 227"
Error starting daemon: error initializing graphdriver: driver not supported


Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 825, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 785, in get_image_info
    images, supervisor_version = get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 668, in get_images_and_supervisor_version
    return _get_images_and_supervisor_version(inner_image_path)
  File "/usr/src/app/preload.py", line 644, in _get_images_and_supervisor_version
    with docker_context_manager(driver, mountpoint):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 511, in docker_context_manager
    running_dockerd = start_docker_daemon(storage_driver, docker_dir)
  File "/usr/src/app/preload.py", line 480, in start_docker_daemon
    running_dockerd.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmppe4ea8sb/docker --host=tcp://0.0.0.0:56017

  STDOUT:


  STDERR:
time="2018-12-13T09:49:44.170731602Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2018-12-13T09:49:44.173455723Z" level=info msg="libcontainerd: new containerd process, pid: 227"
Error starting daemon: error initializing graphdriver: driver not supported

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io

```

**Comment by drewcovi** [comment]
Any updates on this? Or is the only solution to use an old version of Docker?

**Comment by tafli** [comment]
Does not relate to macOS only, got the same problem on Linux with docker v19.03.5-ce. Any updates on this?
