### ISSUE TITLE
Balena preload fails on Mac

### ISSUE THREAD

**Issue by drewcovi** [balena-io/balena-preload#210]
Running the latest Docker for mac and the latest balena-cli

`Docker version 19.03.2, build 6a30dfc`
`balena -v 11.12.0`
MacOS 10.14.5 

```
rror: Step 1/7 : FROM docker:17.10.0-ce-dind
 ---> 9769e0f3f9cb
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Running in 76f8dc772458
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.5-44-gda55e27396 [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
v3.6.5-34-gf0ba0b43d5 [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
OK: 8451 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/29) Installing libattr (2.4.47-r6)
(2/29) Installing libacl (2.2.52-r3)
(3/29) Installing coreutils (8.27-r0)
(4/29) Installing device-mapper-libs (2.02.168-r3)
(5/29) Installing libseccomp (2.3.2-r0)
(6/29) Installing docker (17.05.0-r0)
Executing docker-17.05.0-r0.pre-install
(7/29) Installing libmagic (5.32-r0)
(8/29) Installing file (5.32-r0)
(9/29) Installing ncurses-terminfo-base (6.0_p20171125-r1)
(10/29) Installing ncurses-terminfo (6.0_p20171125-r1)
(11/29) Installing ncurses-libs (6.0_p20171125-r1)
(12/29) Installing readline (6.3.008-r5)
(13/29) Installing parted (3.2-r5)
(14/29) Installing libbz2 (1.0.6-r5)
(15/29) Installing expat (2.2.0-r1)
(16/29) Installing libffi (3.2.1-r3)
(17/29) Installing gdbm (1.12-r0)
(18/29) Installing sqlite-libs (3.25.3-r0)
(19/29) Installing python3 (3.6.8-r0)
(20/29) Installing libfdisk (2.28.2-r2)
(21/29) Installing libsmartcols (2.28.2-r2)
(22/29) Installing sfdisk (2.28.2-r2)
(23/29) Installing libgcc (6.3.0-r4)
(24/29) Installing popt (1.16-r6)
(25/29) Installing libstdc++ (6.3.0-r4)
(26/29) Installing sgdisk (1.0.1-r1)
(27/29) Installing libmount (2.28.2-r2)
(28/29) Installing findmnt (2.28.2-r2)
(29/29) Installing util-linux (2.28.2-r2)
Executing busybox-1.26.2-r7.trigger
OK: 189 MiB in 63 packages
Removing intermediate container 76f8dc772458
 ---> b2478ccd00fc
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> b7fdabda0ceb
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Running in 31529ae5704c
Collecting sh==1.12.14 (from -r /tmp/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
Installing collected packages: sh
Successfully installed sh-1.12.14
You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 31529ae5704c
 ---> 7236564382cc
Step 5/7 : COPY ./src /usr/src/app
 ---> cbc4b93a778a
Step 6/7 : WORKDIR /usr/src/app
 ---> Running in 1cd95c8deaf8
Removing intermediate container 1cd95c8deaf8
 ---> 2a19bc96de9e
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Running in 1876d3b63c45
Removing intermediate container 1876d3b63c45
 ---> f42e55d4e842
Successfully built f42e55d4e842
Successfully tagged balena/balena-preload:latest
Waiting for Docker to start...
Exception in thread background thread for pid 114:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpptmvhvj3/docker --host=tcp://0.0.0.0:53396

  STDOUT:


  STDERR:
time="2019-09-25T16:30:19.469816533Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2019-09-25T16:30:19.475813031Z" level=info msg="libcontainerd: new containerd process, pid: 132"
Error starting daemon: error initializing graphdriver: driver not supported
```

**Comment by drewcovi** [comment]
dupe of #193
