### ISSUE TITLE
Issue with openBalena

### ISSUE THREAD

**Issue by mexekanez** [balena-io/balena-preload#211]
> balena-preload --app 12 --commit 1234 --api-host visoagent.xyz --api-token 1234 --img balena.img --add-certificate ca.crt
> Building Docker preloader image. [========================] 100%
> 
> 
> 
> / Creating preloader container
> | Starting preloader container
> \ Fetching application 12
> / Reading image information
> \ Resizing partitions and waiting for dockerd to start
> / Cleaning up temporary files
> 
> { Error: (HTTP code 500) server error - Get https://registry.MYDOAMIN.xyz/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
>     at /usr/local/lib/node_modules/balena-preload/node_modules/docker-modem/lib/modem.js:257:17
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/balena-preload/node_modules/docker-modem/lib/modem.js:284:9)
>     at emitNone (events.js:111:20)
>     at IncomingMessage.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9) reason: 'server error', statusCode: 500, json: null }
> 
> Looks like this might be an issue with balena-preload. Please report it at https://github.com/balena-io/balena-preload/issues

from others side all options works well like deploy and etc...

**Comment by mexekanez** [comment]
additional thread with the same issue:

https://forums.balena.io/t/incude-script-in-initial-image/34640/28
